[package]
name = "phenotyper-cli"
description = "CLI for the Phenotyper compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["dsl", "compiler", "cli", "code-generation", "phenotyper"]
categories = ["compilers", "command-line-utilities"]
rust-version.workspace = true

[[bin]]
name = "phenotyper"
path = "src/main.rs"

[dependencies]
phenotyper = { workspace = true, features = ["json-diagnostics"] }
clap.workspace = true
serde_json.workspace = true
