// SPDX-License-Identifier: Apache-2.0
//! Parser module — Rustemo grammar integration and AST construction.
//!
//! The parser is generated by Rustemo from `phenotyper.rustemo`.
//! - The parser tables are generated into `OUT_DIR` during build.
//! - The actions file (`phenotyper_actions.rs`) is in the source tree
//!   and can be manually customized.
//!
//! # Usage
//!
//! ```ignore
//! use phenotyper_core::parser;
//! let ast = parser::parse_pht(source, "file.pht")?;
//! ```

// Include generated parser from OUT_DIR and actions from source tree
rustemo::rustemo_mod!(phenotyper, "/src/parser");

#[allow(unused)]
#[rustfmt::skip]
mod phenotyper_actions;

use rustemo::Parser;

use crate::diagnostic::Diagnostic;
use crate::lexer::source_map::extract_pht_blocks;

/// Parse a `.pht` source string into the Rustemo-generated AST.
///
/// Returns `Ok(ast)` on success, or `Err(diagnostics)` on parse failure.
pub fn parse_pht(source: &str, file: &str) -> Result<phenotyper_actions::File, Vec<Diagnostic>> {
    let parser = phenotyper::PhenotyperParser::new();
    parser
        .parse(source)
        .map_err(|e| rustemo_error_to_diags(e, file))
}

/// Parse a `.md` source string by extracting `pht` blocks and parsing.
///
/// Uses the [`SourceMap`] to remap line numbers in diagnostics.
pub fn parse_md(markdown: &str, file: &str) -> Result<phenotyper_actions::File, Vec<Diagnostic>> {
    let (_blocks, source_map) = extract_pht_blocks(markdown);

    if source_map.source.is_empty() {
        return Err(vec![Diagnostic {
            severity: crate::diagnostic::Severity::Error,
            summary: "no ```pht blocks found in markdown file".to_string(),
            file: file.to_string(),
            line: 0,
            col: 0,
            explanation: Some(
                "the .md file must contain at least one fenced code block tagged 'pht'".to_string(),
            ),
            suggestion: Some("add a ```pht ... ``` block".to_string()),
        }]);
    }

    let parser = phenotyper::PhenotyperParser::new();
    parser.parse(&source_map.source).map_err(|e| {
        let mut diags = rustemo_error_to_diags(e, file);
        // Remap line numbers via source map
        for diag in &mut diags {
            if diag.line > 0 {
                diag.line = source_map.original_line(diag.line);
            }
        }
        diags
    })
}

/// Convert a Rustemo error into our Diagnostic type.
fn rustemo_error_to_diags(err: rustemo::Error, file: &str) -> Vec<Diagnostic> {
    vec![Diagnostic {
        severity: crate::diagnostic::Severity::Error,
        summary: format!("{err}"),
        file: file.to_string(),
        line: 0,
        col: 0,
        explanation: None,
        suggestion: None,
    }]
}

#[cfg(test)]
mod tests;
